name: Max Schroeder - Slack-Me CI/CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: metaldev/mschroeder-wa-slack-me

jobs:
  build-and-test:
    name: Build & Test Slack-Me App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Slack-Me

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up .env and key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        env:
          SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
        run: php artisan test --testdox

  docker:
    name: Build & Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image from root
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Log in to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker push ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker push ${{ env.IMAGE_NAME }}:latest
